--For landuse classifications there are tables containing the landuses, these are stored in a new schema
CREATE SCHEMA IF NOT EXISTS reference_tables;

--Then create the table for landuse
CREATE TABLE IF NOT EXISTS reference_tables.landuse_classifications (
        landuse_id VARCHAR(9) NOT NULL,
        description_en VARCHAR(74) NOT NULL,
        description_id VARCHAR(74) NOT NULL,
        level VARCHAR(5) NOT NULL,
        parent_id VARCHAR(4),
        is_used BOOLEAN DEFAULT True
);

--populate with data
--These are taking from the NLUD calssifcations as url below, accessed 12th August 2019
-- https://land.copernicus.eu/eagle/files/eagle-related-projects/22_NLUD_v44.pdf

-- The is_used column is set based on whether we plan to use a given order/class for urban buildings.

INSERT INTO reference_tables.landuse_classifications
(landuse_id, description_en, description_id, level, parent_id, is_used)
VALUES

-- order
('U010','Agriculture And Fisheries','Agriculture And Fisheries','order',NULL,True),
('U080','Community Services','Community Services','order',NULL,True),
('U120','Defence','Defence','order',NULL,True),
('U020','Forestry','Forestry','order',NULL,False),
('U100','Industry And Business','Industry And Business','order',NULL,True),
('U030','Minerals','Minerals','order',NULL,False),
('U040','Recreation And Leisure','Recreation And Leisure','order',NULL,True),
('U070','Residential','Residential','order',NULL,True),
('U090','Retail','Retail','order',NULL,True),
('U050','Transport','Transport','order',NULL,True),
('U130','Unused Land','Unused Land','order',NULL,False),
('U060','Utilities And Infrastructure','Utilities And Infrastructure','order',NULL,True),
('U110','Vacant And Derelict','Vacant And Derelict','order',NULL,True),
--We have created a landuse order that does not exist for mixed use
('U140','Mixed Use','Mixed Use','order',NULL,True),

-- group
('U011','Agriculture','Agriculture','group','U010', True),
('U012','Fisheries','Fisheries','group','U010', True),
('U021','Managed forest','Managed forest','group','U020', True),
('U022','Un-managed forest','Un-managed forest','group','U020', True),
('U031','Mineral workings and quarries','Mineral workings and quarries','group','U030', True),
('U041','Outdoor amenity and open spaces','Outdoor amenity and open spaces','group','U040', True),
('U042','Amusement and show places','Amusement and show places','group','U040', True),
('U043','Libraries, museums and galleries','Libraries, museums and galleries','group','U040', True),
('U044','Sports facilities and grounds','Sports facilities and grounds','group','U040', True),
('U045','Holiday parks and camps','Holiday parks and camps','group','U040', True),
('U046','Allotments and city farms','Allotments and city farms','group','U040', True),
('U051','Transport tracks and ways','Transport tracks and ways','group','U050', True),
('U052','Transport terminals and interchanges','Transport terminals and interchanges','group','U050', True), -- corrected U054 to U052
('U053','Car parks','Car parks','group','U050', True),
('U054','Vehicle storage','Vehicle storage','group','U050', True), -- corrected U051 to U054
('U055','Goods and freight terminals','Goods and freight terminals','group','U050', True),
('U056','Waterways','Waterways','group','U050', True),
('U061','Energy production and distribution','Energy production and distribution','group','U060', True),
('U062','Water storage and treatment','Water storage and treatment','group','U060', True),
('U063','Refuse disposal','Refuse disposal','group','U060', True),
('U064','Cemeteries and crematoria','Cemeteries and crematoria','group','U060', True),
('U065','Post and telecommunications','Post and telecommunications','group','U060', True),
('U071','Dwellings','Dwellings','group','U070', True),
('U072','Hotels, boarding and guest houses','Hotels, boarding and guest houses','group','U070', True),
('U073','Residential institutions','Residential institutions','group','U070', True),
('U081','Medical and health care services','Medical and health care services','group','U080', True),
('U082','Places of worship','Places of worship','group','U080', True),
('U083','Education','Education','group','U080', True),
('U084','Community services','Community services','group','U080', True),
('U091','Shops','Shops','group','U090', True),
('U092','Financial and professional services','Financial and professional services','group','U090', True),
('U093','Restaurants and cafes','Restaurants and cafes','group','U090', True),
('U094','Public houses, bars and nightclubs','Public houses, bars and nightclubs','group','U090', True),
('U101','Manufacturing','Manufacturing','group','U100', True),
('U102','Offices','Offices','group','U100', True),
('U103','Storage','Storage','group','U100', True),
('U104','Wholesale distribution','Wholesale distribution','group','U100', True),
('U111','Vacant','Vacant','group','U110', True),
('U112','Derelict','Derelict','group','U110', True),
('U121','Defence','Defence','group','U120', True),
('U131','Unused land','Unused land','group','U130', True),

-- class
('AG05A -A','Agricultural research establishment','Agricultural research establishment','class','U011',True),
('AG','Agriculture and fisheries places','Agriculture and fisheries places','class','U011',False),
('AG01A -A','Animal artificial insemination centre','Animal artificial insemination centre','class','U011',False),
('AG01B -A','Animal boarding establishment','Animal boarding establishment','class','U011',False),
('AG02A','Animal breeding places','Animal breeding places','class','U011',True),
('AG01B -B','Animal clipping and manicure establishment','Animal clipping and manicure establishment','class','U011',True),
('AG01A -B','Animal dipping place','Animal dipping place','class','U011',True),
('AG02','Animal living places','Animal living places','class','U011',True),
('AG03A','Animal milking places','Animal milking places','class','U011',True),
('AG03','Animal product processing places','Animal product processing places','class','U011',True),
('AG03F -A','Animal product waste store','Animal product waste store','class','U011',True),
('AG03F -B','Animal product waste treatment places','Animal product waste treatment places','class','U011',True),
('AG03F','Animal products waste handling places','Animal products waste handling places','class','U011',True),
('AG02B','Animal rearing places','Animal rearing places','class','U011',True),
('AG01A','Animal service places','Animal service places','class','U011',True),
('AG01','Animal service places','Animal service places','class','U011',True),
('AG03B','Animal shearing places','Animal shearing places','class','U011',True),
('AG03C','Animal slaughtering places','Animal slaughtering places','class','U011',True),
('AG03C-A','Animal stunning and killing places','Animal stunning and killing places','class','U011',True),
('AG01B','Animal welfare places','Animal welfare places','class','U011',True),
('AG06A','Arable farm places','Arable farm places','class','U011',True),
('AG02B -A','Bedding and waste removal','Bedding and waste removal','class','U011',True),
('AG01A -C','Blacksmith premises','Blacksmith premises','class','U011',True),
('AG06A -A','Cereal crops','Cereal crops','class','U011',False),
('AG07A -A','Cereal crops store','Cereal crops store','class','U011',True),
('AG07A','Crop conditioning grading and storage places','Crop conditioning grading and storage places','class','U011',True),
('AG07','Crop processing places','Crop processing places','class','U011',True),
('AG06','Cultivated places','Cultivated places','class','U011',True),
('AG03D-A','Egg grading place','Egg grading place','class','U011',True),
('AG06A -B','Fallow land','Fallow land','class','U011',False),
('AG03E','Feed handling places','Feed handling places','class','U011',True),
('AG03E -A','Feed preparation place','Feed preparation place','class','U011',True),
('AG03E -B','Feed storage place','Feed storage place','class','U011',True),
('AG02B -B','Feeding','Feeding','class','U011',True),
('AG03D-B','Fish sorting place','Fish sorting place','class','U011',True),
('AG06B -B','Flower bed','Flower bed','class','U011',False),
('AG07A -B','Fruit crops','Fruit crops','class','U011',False),
('AG06B -C','Glass house','Glass house','class','U011',True),
('AG08A','Grazing places','Grazing places','class','U011',False),
('AG06A -C','Green forage crops place','Green forage crops place','class','U011',False),
('AG07A -C','Green forage crops store','Green forage crops store','class','U011',False),
('AG06B -D','Hop field','Hop field','class','U011',False),
('AG06B','Horticultural places','Horticultural places','class','U011',True),
('AG02B -C','Isolation (animal living place)','Isolation (animal living place)','class','U011',False),
('AG03C-B','Knackering place','Knackering place','class','U011',True),
('AG03A -A','Milk extraction place','Milk extraction place','class','U011',True),
('AG03A -B','Milk treatment place','Milk treatment place','class','U011',True),
('AG07A -F','Mill and mix building','Mill and mix building','class','U011',True),
('AG06B -E','Mixed market garden','Mixed market garden','class','U011',False),
('AG08','Non cultivated places','Non cultivated places','class','U011',False),
('AG06B -F','Nursery','Nursery','class','U011',False),
('AG06B -G', 'Orchard with arable land', 'Orchard with arable land', 'class', 'U011', False),
('AG06B -H', 'Orchard with grass', 'Orchard with grass', 'class', 'U011', False),
('AG06B -I', 'Orchard with market garden', 'Orchard with market garden', 'class', 'U011', False),
('AG07A -G', 'Packing and sorting crop processing place', 'Packing and sorting crop processing place', 'class', 'U011', True),
('AG03D', 'Packing places animal products', 'Packing places animal products', 'class', 'U011', True),
('AG02A -C', 'Parturition place', 'Parturition place', 'class', 'U011', True),
('AG08A -A', 'Permanent pasture', 'Permanent pasture', 'class', 'U011', False),
('AG03C-C', 'Processing place animal slaughtering place', 'Processing place animal slaughtering place', 'class', 'U011', True),
('AG06A -D', 'Pulse crops place', 'Pulse crops place', 'class', 'U011', False),
('AG07A -D', 'Pulse crops store', 'Pulse crops store', 'class', 'U011', True),
('AG01B -C', 'Quarantine place, animal', 'Quarantine place, animal', 'class', 'U011', True),
('AG06A -E', 'Root crops place', 'Root crops place', 'class', 'U011', True),
('AG07A -E', 'Root crops store', 'Root crops store', 'class', 'U011', True),
('AG08A -B', 'Rough grazing', 'Rough grazing', 'class', 'U011', False),
('AG02A -D', 'Service pen', 'Service pen', 'class', 'U011', False),
('AG06B -J', 'Soft fruit place', 'Soft fruit place', 'class', 'U011', False),
('AG07A -H', 'Vegetable crop conditioning and storage', 'Vegetable crop conditioning and storage', 'class', 'U011', True),
('AG06B -K', 'Vegetable field', 'Vegetable field', 'class', 'U011', False),
('AG01B -D', 'Veterinary hospital', 'Veterinary hospital', 'class', 'U011', True),
('AG01B -E', 'Veterinary surgery', 'Veterinary surgery', 'class', 'U011', True),
('AG02B -E', 'Weighing place', 'Weighing place', 'class', 'U011', True),
('AG03B -A', 'Wool grading place', 'Wool grading place', 'class', 'U011', True),
('AG03B -B', 'Wool removal place', 'Wool removal place', 'class', 'U011', True),
('AG02A -A', 'Fish farm', 'Fish farm', 'class', 'U012', True),
('AG04A', 'Fishery places', 'Fishery places', 'class', 'U012', True),
('AG02A -B', 'Hatchery', 'Hatchery', 'class', 'U012', False),
('AG04A -A', 'Net fishery place', 'Net fishery place', 'class', 'U012', True),
('AG04A -B', 'Pot and other inshore or estuarial fishing place', 'Pot and other inshore or estuarial fishing place', 'class', 'U012', True),
('AG02B -D', 'Rearing pond', 'Rearing pond', 'class', 'U012', False),
('AG04A -C', 'Rod and line fishery place', 'Rod and line fishery place', 'class', 'U012', True),
('AG04', 'Wild life capturing places', 'Wild life capturing places', 'class', 'U012', True),
('MA06A -A', 'Abrasives and other building materials manufacturing place', 'Abrasives and other building materials manufacturing place', 'class', 'U101', True),
('MA04E -A', 'Aerospace equipment manufacturing or repairing place', 'Aerospace equipment manufacturing or repairing place', 'class', 'U101', True),
('MA04A -A', 'Agricultural machinery manufacturing place', 'Agricultural machinery manufacturing place', 'class', 'U101', True),
('MA01B -A', 'Aluminium and aluminium alloy manufacturing', 'Aluminium and aluminium alloy manufacturing', 'class', 'U101', True),
('MA02A -A', 'Animal and poultry food manufacturing place', 'Animal and poultry food manufacturing place', 'class', 'U101', True),
('MA02A -B', 'Bacon curing, meat and fish product manufacturing place', 'Bacon curing, meat and fish product manufacturing place', 'class', 'U101', True),
('MA07A -A', 'Bedding and soft furnishings manufacturing place', 'Bedding and soft furnishings manufacturing place', 'class', 'U101', True),
('MA02A -C', 'Biscuit manufacturing', 'Biscuit manufacturing', 'class', 'U101', True),
('MA04F -D', 'Bolts, nuts, screws, rivets etc. manufacturing place', 'Bolts, nuts, screws, rivets etc. manufacturing place', 'class', 'U101', True),
('MA02A -D', 'Bread and flour confectionery manufacturing place', 'Bread and flour confectionery manufacturing place', 'class', 'U101', True),
('MA02A -E', 'Brewery', 'Brewery', 'class', 'U101', True),
('MA06A -B', 'Bricks, fireclay and refractory goods manufacturing place', 'Bricks, fireclay and refractory goods manufacturing place', 'class', 'U101', True),
('MA06A', 'Bricks, pottery, glass, cement manufacturing places', 'Bricks, pottery, glass, cement manufacturing places', 'class', 'U101', True),
('MA04C-A', 'Broadcast receiving and sound reproducing equipment manufacturing', 'Broadcast receiving and sound reproducing equipment manufacturing', 'class', 'U101', True),
('MA08A -A', 'Brushes and brooms manufacturing place', 'Brushes and brooms manufacturing place', 'class', 'U101', True),
('MA04F -A', 'Can and metal box manufacturing place', 'Can and metal box manufacturing place', 'class', 'U101', True),
('MA05A -A', 'Carpet manufacturing place', 'Carpet manufacturing place', 'class', 'U101', True),
('MA06A -C', 'Cement manufacturing place', 'Cement manufacturing place', 'class', 'U101', True),
('MA03A', 'Chemical and allied industries manufacturing places', 'Chemical and allied industries manufacturing places', 'class', 'U101', True),
('MA05C', 'Clothing and footwear manufacturing places', 'Clothing and footwear manufacturing places', 'class', 'U101', True),
('MA05', 'Clothing, textiles, leather, footwear and fur goods manufacturing places', 'Clothing, textiles, leather, footwear and fur goods manufacturing places', 'class', 'U101', True),
('MA01A', 'Coal and petroleum processing places', 'Coal and petroleum processing places', 'class', 'U101', True),
('MA01', 'Coal, oil and metal processing places', 'Coal, oil and metal processing places', 'class', 'U101', True),
('MA02A -F', 'Cocoa, chocolate and sugar confectionery manufacturing place', 'Cocoa, chocolate and sugar confectionery manufacturing place', 'class', 'U101', True),
('MA01A -A', 'Coke ovens and solid fuel manufacturing place', 'Coke ovens and solid fuel manufacturing place', 'class', 'U101', True),
('MA09A -A', 'Construction and demolition site', 'Construction and demolition site', 'class', 'U101', True),
('MA04A -B', 'Construction and earth moving equipment manufacturing place', 'Construction and earth moving equipment manufacturing place', 'class', 'U101', True),
('MA09', 'Construction places', 'Construction places', 'class', 'U101', True),
('MA09A', 'Construction places', 'Construction places', 'class', 'U101', True),
('MA01B -B', 'Copper, brass and other copper alloy manufacturing place', 'Copper, brass and other copper alloy manufacturing place', 'class', 'U101', True),
('MA04F -B', 'Cutlery and plated tableware manufacturing place', 'Cutlery and plated tableware manufacturing place', 'class', 'U101', True),
('MA05C-A', 'Dresses, lingerie, infants wear etc. manufacturing place', 'Dresses, lingerie, infants wear etc. manufacturing place', 'class', 'U101', True),
('MA03A -A', 'Dyestuffs and pigments manufacturing place', 'Dyestuffs and pigments manufacturing place', 'class', 'U101', True),
('MA04C-B', 'Electric appliances primarily for domestic use manufacturing places', 'Electric appliances primarily for domestic use manufacturing places', 'class', 'U101', True),
('MA04C', 'Electrical engineering places', 'Electrical engineering places', 'class', 'U101', True),
('MA04C-C', 'Electrical machinery manufacturing place', 'Electrical machinery manufacturing place', 'class', 'U101', True),
('MA04C-D', 'Electronic computers manufacturing place', 'Electronic computers manufacturing place', 'class', 'U101', True),
('MA04', 'Engineering places', 'Engineering places', 'class', 'U101', True),
('MA03A -B', 'Explosives and fireworks manufacturing place', 'Explosives and fireworks manufacturing place', 'class', 'U101', True),
('MA03A -C', 'Fertilizer manufacturing place', 'Fertilizer manufacturing place', 'class', 'U101', True),
('MA02A', 'Food, drink and tobacco manufacturing place', 'Food, drink and tobacco manufacturing place', 'class', 'U101', True),
('MA05C-B', 'Footwear manufacturing place', 'Footwear manufacturing place', 'class', 'U101', True),
('MA02A -G', 'Fruit and vegetable product manufacturing place', 'Fruit and vegetable product manufacturing place', 'class', 'U101', True),
('MA05B -A', 'Fur goods manufacturing place', 'Fur goods manufacturing place', 'class', 'U101', True),
('MA07A -B', 'Furniture and upholstery manufacturing place', 'Furniture and upholstery manufacturing place', 'class', 'U101', True),
('MA03A -D', 'General chemical manufacturing place', 'General chemical manufacturing place', 'class', 'U101', True),
('MA06A -D', 'Glass manufacturing place', 'Glass manufacturing place', 'class', 'U101', True),
('MA02A -H', 'Grain mill', 'Grain mill', 'class', 'U101', True),
('MA05C-C', 'Hats, cap and millinery manufacturing place', 'Hats, cap and millinery manufacturing place', 'class', 'U101', True),
('MA05A -B', 'Hosiery and other knitted goods manufacturing place', 'Hosiery and other knitted goods manufacturing place', 'class', 'U101', True),
('MA10A -A', 'Industrial research laboratory', 'Industrial research laboratory', 'class', 'U101', True),
('MA04A -C', 'Industrial services equipment manufacturing place', 'Industrial services equipment manufacturing place', 'class', 'U101', True),
('MA04B', 'Instrument engineering places', 'Instrument engineering places', 'class', 'U101', True),
('MA04C-E', 'Insulated wires and cables manufacturing place', 'Insulated wires and cables manufacturing place', 'class', 'U101', True),
('MA01B -C', 'Iron and steel manufacturing place', 'Iron and steel manufacturing place', 'class', 'U101', True),
('MA04F -C', 'Jewellery and precious metal manufacturing place', 'Jewellery and precious metal manufacturing place', 'class', 'U101', True),
('MA05A -C', 'Jute manufacturing place', 'Jute manufacturing place', 'class', 'U101', True),
('MA05A -B', 'Knitted goods manufacturing place', 'Knitted goods manufacturing place', 'class', 'U101', True),
('MA05A -D', 'Lace manufacturing place', 'Lace manufacturing place', 'class', 'U101', True),
('MA01B -D', 'Lead manufacturing place', 'Lead manufacturing place', 'class', 'U101', True),
('MA05B -C', 'Leather tanning and dressing and fellmongery place', 'Leather tanning and dressing and fellmongery place', 'class', 'U101', True),
('MA05B', 'Leather and fur goods manufacturing places', 'Leather and fur goods manufacturing places', 'class', 'U101', True),
('MA05B -B', 'Leather goods manufacturing place', 'Leather goods manufacturing place', 'class', 'U101', True),
('MA08A -B', 'Linoleum, plastics floor covering, leather cloth manufacturing place', 'Linoleum, plastics floor covering, leather cloth manufacturing place', 'class', 'U101', True),
('MA04E -B', 'Locomotives and railway track equipment manufacturing place', 'Locomotives and railway track equipment manufacturing place', 'class', 'U101', True),
('MA01A -B', 'Lubricating oil and grease manufacturing place', 'Lubricating oil and grease manufacturing place', 'class', 'U101', True),
('MA05A -E', 'Made up textile manufacturing place', 'Made up textile manufacturing place', 'class', 'U101', True),
('MA05A -F', 'Man made fibre production manufacturing place', 'Man made fibre production manufacturing place', 'class', 'U101', True),
('MA10A', 'Manufacturing research establishments', 'Manufacturing research establishments', 'class', 'U101', True),
('MA12A -A', 'Manufacturing storage place', 'Manufacturing storage place', 'class', 'U101', True),
('MA12A', 'Manufacturing storage places', 'Manufacturing storage places', 'class', 'U101', True),
('MA11A', 'Manufacturing waste disposal places', 'Manufacturing waste disposal places', 'class', 'U101', True),
('MA11A -A', 'Manufacturing waste tip', 'Manufacturing waste tip', 'class', 'U101', True),
('MA04A', 'Mechanical engineering places', 'Mechanical engineering places', 'class', 'U101', True),
('MA04A -D', 'Mechanical handling equipment manufacturing place', 'Mechanical handling equipment manufacturing place', 'class', 'U101', True),
('MA01B', 'Metal processing places basic forms', 'Metal processing places basic forms', 'class', 'U101', True),
('MA04A -E', 'Metal working machine tools manufacturing place', 'Metal working machine tools manufacturing place', 'class', 'U101', True),
('MA02A -I', 'Milk and milk product manufacturing place', 'Milk and milk product manufacturing place', 'class', 'U101', True),
('MA01A -C', 'Mineral oil refinery', 'Mineral oil refinery', 'class', 'U101', True),
('MA08A -C', 'Miscellaneous goods manufacturing place', 'Miscellaneous goods manufacturing place', 'class', 'U101', True),
('MA08A -D', 'Miscellaneous stationers goods manufacturing place', 'Miscellaneous stationers goods manufacturing place', 'class', 'U101', True),
('MA07A -C', 'Miscellaneous wood and cork manufacturing place', 'Miscellaneous wood and cork manufacturing place', 'class', 'U101', True),
('MA04E -C', 'Motor cycle, tricycle and pedal cycle manufacturing place', 'Motor cycle, tricycle and pedal cycle manufacturing place', 'class', 'U101', True),
('MA04E -D', 'Motor vehicle manufacturing place', 'Motor vehicle manufacturing place', 'class', 'U101', True),
('MA05A -G', 'Narrow fabric manufacturing place', 'Narrow fabric manufacturing place', 'class', 'U101', True),
('MA04A -F', 'Office machinery manufacturing place', 'Office machinery manufacturing place', 'class', 'U101', True),
('MA04A -G', 'Ordnance and small arms manufacturing place', 'Ordnance and small arms manufacturing place', 'class', 'U101', True),
('MA05C-D', 'Overalls and men's shirts and underwear manufacturing place', 'Overalls and men's shirts and underwear manufacturing place', 'class', 'U101', True),
('MA07B -B', 'Packaging products of paper and associated materials manufacturing place', 'Packaging products of paper and associated materials manufacturing place', 'class', 'U101', True),
('MA03A -E', 'Paint manufacturing place', 'Paint manufacturing place', 'class', 'U101', True),
('MA07B -C', 'Paper and board manufacturing place', 'Paper and board manufacturing place', 'class', 'U101', True),
('MA07B', 'Paper, printing and publishing works', 'Paper, printing and publishing works', 'class', 'U101', True),
('MA07B -D', 'Periodical and newspaper printing and publishing works', 'Periodical and newspaper printing and publishing works', 'class', 'U101', True),
('MA03A -F', 'Pharmaceutical chemicals and preparation manufacturing place', 'Pharmaceutical chemicals and preparation manufacturing place', 'class', 'U101', True),
('MA04B -A', 'Photographic and document copying equipment manufacturing place', 'Photographic and document copying equipment manufacturing place', 'class', 'U101', True),
('MA06A -E', 'Pottery manufacturing place', 'Pottery manufacturing place', 'class', 'U101', True),
('MA04A -H', 'Prime movers manufacturing place', 'Prime movers manufacturing place', 'class', 'U101', True),
('MA04A -I', 'Pumps, valves and compressor manufacturing place', 'Pumps, valves and compressor manufacturing place', 'class', 'U101', True),
('MA04C-F', 'Radio and electronic capital goods manufacturing place', 'Radio and electronic capital goods manufacturing place', 'class', 'U101', True),
('MA04C-G', 'Radio, radar and electronic capital goods manufacturing place', 'Radio, radar and electronic capital goods manufacturing place', 'class', 'U101', True),
('MA04E -E', 'Railway carriages and wagons and trams manufacturing place', 'Railway carriages and wagons and trams manufacturing place', 'class', 'U101', True),
('MA05A -H', 'Rope, twine and net manufacturing place', 'Rope, twine and net manufacturing place', 'class', 'U101', True),
('MA08A -E', 'Rubber goods manufacturing place', 'Rubber goods manufacturing place', 'class', 'U101', True),
('MA04B -C', 'Scientific and industrial instruments and systems manufacturing', 'Scientific and industrial instruments and systems manufacturing', 'class', 'U101', True),
('MA04D-A', 'Shipbuilding and marine engineering place', 'Shipbuilding and marine engineering place', 'class', 'U101', True),
('MA07A -D', 'Shop and office fittings manufacturing place', 'Shop and office fittings manufacturing place', 'class', 'U101', True),
('MA04F -E', 'Small tools, implements and gauges manufacturing place', 'Small tools, implements and gauges manufacturing place', 'class', 'U101', True),
('MA03A -G', 'Soap, detergent and fat splitting and distillation manufacturing place', 'Soap, detergent and fat splitting and distillation manufacturing place', 'class', 'U101', True),
('MA02A -J', 'Soft drinks manufacturing place', 'Soft drinks manufacturing place', 'class', 'U101', True),
('MA05A -I', 'Spinning and doubling cotton and flax systems manufacturing place', 'Spinning and doubling cotton and flax systems manufacturing place', 'class', 'U101', True),
('MA07B -A', 'Stationery manufacturing place', 'Stationery manufacturing place', 'class', 'U101', True),
('MA02A -K', 'Sugar refinery', 'Sugar refinery', 'class', 'U101', True),
('MA04B -B', 'Surgical instruments and appliances manufacturing place', 'Surgical instruments and appliances manufacturing place', 'class', 'U101', True),
('MA03A -H', 'Synthetic resins, plastics and synthetic rubber manufacturing place', 'Synthetic resins, plastics and synthetic rubber manufacturing place', 'class', 'U101', True),
('MA05C-E', 'Tailored outerwear manufacturing place', 'Tailored outerwear manufacturing place', 'class', 'U101', True),
('MA04C-H', 'Telegraph and telephone apparatus and equipment manufacturing place', 'Telegraph and telephone apparatus and equipment manufacturing place', 'class', 'U101', True),
('MA05A -J', 'Textile finishing place', 'Textile finishing place', 'class', 'U101', True),
('MA04A -J', 'Textile machinery and accessories manufacturing place', 'Textile machinery and accessories manufacturing place', 'class', 'U101', True),
('MA05A', 'Textile manufacturing places', 'Textile manufacturing places', 'class', 'U101', True),
('MA07A', 'Timber and furniture works', 'Timber and furniture works', 'class', 'U101', True),
('MA07', 'Timber furniture, paper, printing and publishing works', 'Timber furniture, paper, printing and publishing works', 'class', 'U101', True),
('MA07A -E', 'Timber works', 'Timber works', 'class', 'U101', True),
('MA02A -L', 'Tobacco manufacturing place', 'Tobacco manufacturing place', 'class', 'U101', True),
('MA03A -I', 'Toilet preparation manufacturing place', 'Toilet preparation manufacturing place', 'class', 'U101', True),
('MA08A -F', 'Toys, games, children's carriages and sports equipment manufacturing place', 'Toys, games, children's carriages and sports equipment manufacturing place', 'class', 'U101', True),
('MA02A -M', 'Vegetable, animal oil and fat manufacturing place', 'Vegetable, animal oil and fat manufacturing place', 'class', 'U101', True),
('MA04E', 'Vehicle engineering places', 'Vehicle engineering places', 'class', 'U101', True),
('MA04B -D', 'Watches and clocks manufacturing place', 'Watches and clocks manufacturing place', 'class', 'U101', True),
('MA05C-F', 'Weatherproof outerwear manufacturing place', 'Weatherproof outerwear manufacturing place', 'class', 'U101', True),
('MA05A -K', 'Weaving of cotton, linen and man made fibres manufacturing place', 'Weaving of cotton, linen and man made fibres manufacturing place', 'class', 'U101', True),
('MA04E -F', 'Wheeled tractor manufacturing place', 'Wheeled tractor manufacturing place', 'class', 'U101', True),
('MA04F -F', 'Wire manufacturing place', 'Wire manufacturing place', 'class', 'U101', True),
('MA07A -F', 'Wooden containers and baskets manufacturing place', 'Wooden containers and baskets manufacturing place', 'class', 'U101', True),
('MA05A -L', 'Woollen and worsted manufacturing place', 'Woollen and worsted manufacturing place', 'class', 'U101', True),
('OF03A -A', 'Business discussion places', 'Business discussion places', 'class', 'U102', True),
('OF03A', 'Business meeting places', 'Business meeting places', 'class', 'U102', True),
('OF03', 'Business meeting places', 'Business meeting places', 'class', 'U102', True),
('OF01A -A', 'Central government administration office', 'Central government administration office', 'class', 'U102', True),
('OF01A', 'General offices', 'General offices', 'class', 'U102', True),
('OF01A -B', 'Local government administration office', 'Local government administration office', 'class', 'U102', True),
('OF01A -C', 'Manufacturing administration office', 'Manufacturing administration office', 'class', 'U102', True),
('OF', 'Offices', 'Offices', 'class', 'U102', True),
('OF01A -D', 'Professional services office', 'Professional services office', 'class', 'U102', True),
('OF04A -A', 'Studio', 'Studio', 'class', 'U102', True),
('ST01A -A', 'Agricultural machinery store', 'Agricultural machinery store', 'class', 'U103', True),
('ST02A -A', 'Builders yard', 'Builders yard', 'class', 'U103', True),
('ST01A -B', 'Building equipment store', 'Building equipment store', 'class', 'U103', True),
('ST02A', 'Bulk material stores', 'Bulk material stores', 'class', 'U103', True),
('ST02A -B', 'Cleaning materials store', 'Cleaning materials store', 'class', 'U103', True),
('ST01A -C', 'Engineering equipment store', 'Engineering equipment store', 'class', 'U103', True),
('ST01A', 'Equipment stores', 'Equipment stores', 'class', 'U103', True),
('ST03A -A', 'Furniture depository', 'Furniture depository', 'class', 'U103', True),
('ST03A -B', 'General goods store', 'General goods store', 'class', 'U103', True),
('ST01A -D', 'Industrial and office machinery store', 'Industrial and office machinery store', 'class', 'U103', True),
('ST02', 'Material stores', 'Material stores', 'class', 'U103', True),
('ST03A -C', 'Refrigerated store', 'Refrigerated store', 'class', 'U103', True),
('ST01A -E', 'Sports equipment store', 'Sports equipment store', 'class', 'U103', True),
('ST', 'Storage', 'Storage', 'class', 'U103', True),
('WH01B -A', 'Agricultural machinery dealer’s place', 'Agricultural machinery dealer’s place', 'class', 'U104', True),
('WH01A -C', 'Builders merchant's place', 'Builders merchant's place', 'class', 'U104', True),
('WH01A', 'Bulk dealing places', 'Bulk dealing places', 'class', 'U104', True),
('WH01A -A', 'Coal and oil dealer's place', 'Coal and oil dealer's place', 'class', 'U104', True),
('WH01A -B', 'Corn, seed and agricultural supplies dealer's place', 'Corn, seed and agricultural supplies dealer's place', 'class', 'U104', True),
('WH01', 'Dealing in industrial materials, machinery and livestock places', 'Dealing in industrial materials, machinery and livestock places', 'class', 'U104', True),
('WH02A', 'Food and drink wholesaling places', 'Food and drink wholesaling places', 'class', 'U104', True),
('WH02A -A', 'Grocery and provisions confectionery and drinks wholesaling', 'Grocery and provisions confectionery and drinks wholesaling', 'class', 'U104', True),
('WH01B -B', 'Hides, skin and leather dealer's place', 'Hides, skin and leather dealer's place', 'class', 'U104', True),
('WH01C-A', 'Horses and livestock dealer', 'Horses and livestock dealer', 'class', 'U104', True),
('WH01C', 'Horses and livestock dealing places', 'Horses and livestock dealing places', 'class', 'U104', True),
('WH01B', 'Industrial materials and other machinery dealing places', 'Industrial materials and other machinery dealing places', 'class', 'U104', True),
('WH02B -A', 'Petroleum products wholesaling place', 'Petroleum products wholesaling place', 'class', 'U104', True),
('WH01B -C', 'Scrap and waste dealer', 'Scrap and waste dealer', 'class', 'U104', True),
('WH01B -D', 'Timber dealer's place', 'Timber dealer's place', 'class', 'U104', True),
('WH02', 'Wholesale distribution places', 'Wholesale distribution places', 'class', 'U104', True),
('UL02A', 'Unused buildings', 'Unused buildings', 'class', 'U111', True),
('UL01B', 'Unused formerly developed land', 'Unused formerly developed land', 'class', 'U111', False),
('UL01B -A', 'Cleared site', 'Cleared site', 'class', 'U111', True),
('UL01B -C', 'Protected land unused', 'Protected land unused', 'class', 'U111', True),
('UL02A -B', 'Vacant building', 'Vacant building', 'class', 'U111', True),
('UL02A -A', 'Abandoned building', 'Abandoned building', 'class', 'U112', True),
('UL01B -B', 'Mineral excavation or pit dry', 'Mineral excavation or pit dry', 'class', 'U112', True),
('UL02A -A', 'Ruined building', 'Ruined building', 'class', 'U112', True),
('UL01B -D', 'Spoilt land', 'Spoilt land', 'class', 'U112', True),
('UL01B -E', 'Waste heap or tip', 'Waste heap or tip', 'class', 'U112', True),
('DF01', 'Defence establishments', 'Defence establishments', 'class', 'U121', True),
('DF01A', 'Defence training places', 'Defence training places', 'class', 'U121', True),
('DF01A -A', 'Live firing military training area', 'Live firing military training area', 'class', 'U121', True),
('UL01A -A', 'Beach or sand dune', 'Beach or sand dune', 'class', 'U131', False),
('UL01C-A', 'Canal unused', 'Canal unused', 'class', 'U131', False),
('UL01A -B', 'Cliff or natural outcrop', 'Cliff or natural outcrop', 'class', 'U131', False),
('UL01C-B', 'Dock unused', 'Dock unused', 'class', 'U131', False),
('UL01A -C', 'Grass land', 'Grass land', 'class', 'U131', False),
('UL01A -D', 'Heath and moorland', 'Heath and moorland', 'class', 'U131', False),
('UL01C-C', 'Mineral excavation or pit wet', 'Mineral excavation or pit wet', 'class', 'U131', False),
('UL01A -E', 'Peat, bog, freshwater marsh and swamp', 'Peat, bog, freshwater marsh and swamp', 'class', 'U131', False),
('UL01C-D', 'Pond or lake', 'Pond or lake', 'class', 'U131', False),
('UL01A -F', 'Salt marsh unused', 'Salt marsh unused', 'class', 'U131', False),
('UL01', 'Unused land and water', 'Unused land and water', 'class', 'U131', False),
('UL01A', 'Unused land in natural or semi natural state', 'Unused land in natural or semi natural state', 'class', 'U131', False),
('UL01C', 'Unused water', 'Unused water', 'class', 'U131', False),
('UL01C-E', 'Water course', 'Water course', 'class', 'U131', False),
('UL01A -G', 'Woodland and scrub', 'Woodland and scrub', 'class', 'U131', False),
('AG08B -A', 'Coniferous forest', 'Coniferous forest', 'class', 'U022', False),
('AG08B -D', 'Deciduous forest', 'Deciduous forest', 'class', 'U022', False),
('AG08B', 'Forestry places', 'Forestry places', 'class', 'U022', False),
('AG08B -E', 'Mixed forest', 'Mixed forest', 'class', 'U022', False),
('AG08B -B', 'Coppice', 'Coppice', 'class', 'U021', False),
('AG08B -C', 'Coppice with standards', 'Coppice with standards', 'class', 'U021', False),
('AG08B -F', 'Tree nursery', 'Tree nursery', 'class', 'U021', False),
('MI01D-A', 'Aggregate and stone handling installation', 'Aggregate and stone handling installation', 'class', 'U031', True),
('MI01A -A', 'Chalk working', 'Chalk working', 'class', 'U031', False),
('MI01A -B', 'China clay working', 'China clay working', 'class', 'U031', False),
('MI01C-A', 'China clay waste tip and settlement lagoon', 'China clay waste tip and settlement lagoon', 'class', 'U031', False),
('MI01A -C', 'Clay and shale working', 'Clay and shale working', 'class', 'U031', False),
('MI01A -D', 'Coal mine working', 'Coal mine working', 'class', 'U031', False),
('MI01D-B', 'Coal handling installation', 'Coal handling installation', 'class', 'U031', True),
('MI01C-B', 'Coal waste tip and settlement lagoon', 'Coal waste tip and settlement lagoon', 'class', 'U031', False),
('MI01B -A', 'Colliery headgear', 'Colliery headgear', 'class', 'U031', True),
('MI01A -E', 'Gypsum/Anhydrite working', 'Gypsum/Anhydrite working', 'class', 'U031', False),
('MI01A -F', 'Igneous rock working', 'Igneous rock working', 'class', 'U031', False),
('MI01D-C', 'Iron ore handling installation', 'Iron ore handling installation', 'class', 'U031', True),
('MI01A -G', 'Limestone working', 'Limestone working', 'class', 'U031', True),
('MI01', 'Mineral extraction places', 'Mineral extraction places', 'class', 'U031', False),
('MI01D-E', 'Mineral fertiliser handling installation', 'Mineral fertiliser handling installation', 'class', 'U031', True),
('MI01D-D', 'Non ferrous ore handling installation', 'Non ferrous ore handling installation', 'class', 'U031', True),
('MI01D-F', 'Oil and gas handling installation', 'Oil and gas handling installation', 'class', 'U031', True),
('MI01B -B', 'Oil and gas well head', 'Oil and gas well head', 'class', 'U031', True),
('MI01B -C', 'Salt and brine pumping installation', 'Salt and brine pumping installation', 'class', 'U031', True),
('MI01A -H', 'Sand and gravel working', 'Sand and gravel working', 'class', 'U031', False),
('MI01A -I', 'Sandstone working', 'Sandstone working', 'class', 'U031', False),
('MI01A -K', 'Silica and moulding sand working', 'Silica and moulding sand working', 'class', 'U031', False),
('MI01A -L', 'Slate working', 'Slate working', 'class', 'U031', False),
('MI01C-C', 'Slate waste tip', 'Slate waste tip', 'class', 'U031', False),
('MI01B', 'Surface installations for underground mineral workings', 'Surface installations for underground mineral workings', 'class', 'U031', True),
('MI01A', 'Surface mineral workings', 'Surface mineral workings', 'class', 'U031', False),
('MI01A -M', 'Vein mineral working', 'Vein mineral working', 'class', 'U031', False),
('MI01C-D', 'Vein mineral waste tip and settlement lagoon', 'Vein mineral waste tip and settlement lagoon', 'class', 'U031', False),
('MI01C', 'Waste disposal areas from mineral working and processing', 'Waste disposal areas from mineral working and processing', 'class', 'U031', False),
('LE01', 'Amenity, amusement and show places', 'Amenity, amusement and show places', 'class', '#N/A', True),
('LE', 'Recreation and leisure places', 'Recreation and leisure places', 'class', '#N/A', True),
('LE01B -A', 'Ancient monument', 'Ancient monument', 'class', 'U041', True),
('LE01A -A', 'Botanical garden', 'Botanical garden', 'class', 'U041', False),
('LE01A -B', 'Country park', 'Country park', 'class', 'U041', False),
('LE01A -C', 'Gardens', 'Gardens', 'class', 'U041', False),
('LE01B -B', 'Monument', 'Monument', 'class', 'U041', True),
('LE01A', 'Outdoor amenity places', 'Outdoor amenity places', 'class', 'U041', False),
('LE01A -D', 'Park', 'Park', 'class', 'U041', False),
('LE01A -E', 'Picnic site', 'Picnic site', 'class', 'U041', False),
('LE01A -F', 'Recreational open space', 'Recreational open space', 'class', 'U041', False),
('LE01A -G', 'View point', 'View point', 'class', 'U041', False),
('LE01A -A', 'Zoological garden', 'Zoological garden', 'class', 'U041', False),
('LE01C', 'Amusement places', 'Amusement places', 'class', 'U042', True),
('LE01C-A', 'Aquarium', 'Aquarium', 'class', 'U042', True),
('LE01C-C', 'Bingo club', 'Bingo club', 'class', 'U042', True),
('LE01D-A', 'Broadcasting, filming and sound recording studio', 'Broadcasting, filming and sound recording studio', 'class', 'U042', True),
('LE01C-D', 'Children's playground', 'Children's playground', 'class', 'U042', False),
('LE01D-B', 'Cinema', 'Cinema', 'class', 'U042', True),
('LE01D-C', 'Circus', 'Circus', 'class', 'U042', True),
('LE01D-D', 'Concert arena', 'Concert arena', 'class', 'U042', True),
('LE01D-E', 'Countryside interpretation centre', 'Countryside interpretation centre', 'class', 'U042', True),
('LE01C-E', 'Dance hall', 'Dance hall', 'class', 'U042', True),
('LE01D-F', 'Display arena', 'Display arena', 'class', 'U042', True),
('LE01C-F', 'Fun fair', 'Fun fair', 'class', 'U042', True),
('LE01C-G', 'Gaming club', 'Gaming club', 'class', 'U042', True),
('LE01C-H', 'Night club', 'Night club', 'class', 'U042', True),
('LE01D', 'Show places', 'Show places', 'class', 'U042', True),
('LE01D-G', 'Theatre', 'Theatre', 'class', 'U042', True),
('LE02C-A', 'Art gallery', 'Art gallery', 'class', 'U043', True),
('LE02C', 'Galleries', 'Galleries', 'class', 'U043', True),
('LE02A -A', 'Lending library', 'Lending library', 'class', 'U043', True),
('LE02A', 'Libraries', 'Libraries', 'class', 'U043', True),
('LE02', 'Libraries, museums and galleries', 'Libraries, museums and galleries', 'class', 'U043', True),
('LE02B -A', 'Museum', 'Museum', 'class', 'U043', True),
('LE02A -B', 'Reference', 'Reference', 'class', 'U043', True),
('LE03 I', 'Animal training and competing places', 'Animal training and competing places', 'class', 'U044', True),
('LE03G-A', 'Archery range', 'Archery range', 'class', 'U044', True),
('LE03A -A', 'Association football ground', 'Association football ground', 'class', 'U044', True),
('LE03E', 'Athletic game courses', 'Athletic game courses', 'class', 'U044', True),
('LE03D', 'Athletic games arenas', 'Athletic games arenas', 'class', 'U044', True),
('LE03D-A', 'Athletic ground', 'Athletic ground', 'class', 'U044', True),
('LE03B -A', 'Badminton court', 'Badminton court', 'class', 'U044', True),
('LE03C', 'Ball game courses', 'Ball game courses', 'class', 'U044', True),
('LE03B', 'Ball game greens and courts', 'Ball game greens and courts', 'class', 'U044', True),
('LE03A', 'Ball game pitches and grounds', 'Ball game pitches and grounds', 'class', 'U044', True),
('LE03A -B', 'Baseball ground', 'Baseball ground', 'class', 'U044', True),
('LE04B -A', 'Boating facilities', 'Boating facilities', 'class', 'U044', True),
('LE03E -A', 'Bobsleigh course', 'Bobsleigh course', 'class', 'U044', True),
('LE03B -B', 'Bowling green', 'Bowling green', 'class', 'U044', False),
('LE04B -B', 'Canoeing water', 'Canoeing water', 'class', 'U044', False),
('LE03F -A', 'Caving place', 'Caving place', 'class', 'U044', True),
('LE03F', 'Climbing, rambling and caving places', 'Climbing, rambling and caving places', 'class', 'U044', False),
('LE03D-B', 'Combative sports place', 'Combative sports place', 'class', 'U044', True),
('LE03A -C', 'Cricket ground', 'Cricket ground', 'class', 'U044', False),
('LE03B -C', 'Croquet lawn', 'Croquet lawn', 'class', 'U044', False),
('LE03 I -A', 'Cross country horse trial course', 'Cross country horse trial course', 'class', 'U044', False),
('LE03E -B', 'Cross country running course', 'Cross country running course', 'class', 'U044', False),
('LE03H-A', 'Cycling circuit', 'Cycling circuit', 'class', 'U044', True),
('LE03 I -B', 'Dog racing track', 'Dog racing track', 'class', 'U044', True),
('LE03 I -C', 'Dog trials area', 'Dog trials area', 'class', 'U044', True),
('LE03C-B', 'Golf course', 'Golf course', 'class', 'U044', False),
('LE03C-A', 'Golf driving range', 'Golf driving range', 'class', 'U044', False),
('LE03D-C', 'Gymnasium', 'Gymnasium', 'class', 'U044', True),
('LE03A -D', 'Hockey ground', 'Hockey ground', 'class', 'U044', True),
('LE03 I -D', 'Horse racing course', 'Horse racing course', 'class', 'U044', True),
('LE03 I -E', 'Horse show jumping, dressage and trotting arena', 'Horse show jumping, dressage and trotting arena', 'class', 'U044', False),
('LE03 I -F', 'Horse training area', 'Horse training area', 'class', 'U044', True),
('LE03J -A', 'Hunting place', 'Hunting place', 'class', 'U044', False),
('LE03J', 'Hunting and shooting places', 'Hunting and shooting places', 'class', 'U044', True),
('LE03A -E', 'Hurling or shinty grounds', 'Hurling or shinty grounds', 'class', 'U044', True),
('LE03D-D', 'Ice rink', 'Ice rink', 'class', 'U044', True),
('LE03A -F', 'Lacrosse ground', 'Lacrosse ground', 'class', 'U044', True),
('LE03H-B', 'Land sailing area', 'Land sailing area', 'class', 'U044', False),
('LE03', 'Land sport places', 'Land sport places', 'class', 'U044', False),
('LE03H', 'Land vehicle performance places', 'Land vehicle performance places', 'class', 'U044', False),
('LE03B -D', 'Miniature golf course', 'Miniature golf course', 'class', 'U044', True),
('LE03H-C', 'Motor vehicle racing track', 'Motor vehicle racing track', 'class', 'U044', False),
('LE03A -G', 'Polo ground', 'Polo ground', 'class', 'U044', True),
('LE04B -C', 'Power craft water', 'Power craft water', 'class', 'U044', False),
('LE03F -B', 'Rambling and fell walking', 'Rambling and fell walking', 'class', 'U044', False),
('LE03E -C', 'Road running and walking course', 'Road running and walking course', 'class', 'U044', False),
('LE03F -C', 'Rock climbing', 'Rock climbing', 'class', 'U044', True),
('LE04C-A', 'Rod/recreational fishing place', 'Rod/recreational fishing place', 'class', 'U044', False),
('LE03D-E', 'Roller skating rink', 'Roller skating rink', 'class', 'U044', True),
('LE04B -D', 'Rowing water', 'Rowing water', 'class', 'U044', False),
('LE03A -H', 'Rugby football ground', 'Rugby football ground', 'class', 'U044', False),
('LE04B -E', 'Sailing', 'Sailing', 'class', 'U044', True),
('LE03J -B', 'Shooting and stalking area', 'Shooting and stalking area', 'class', 'U044', False),
('LE03E -D', 'Skiing and tobogganing run', 'Skiing and tobogganing run', 'class', 'U044', False),
('LE03G-B', 'Small arms range', 'Small arms range', 'class', 'U044', False),
('LE03B -E', 'Squash court', 'Squash court', 'class', 'U044', True),
('LE04A', 'Swimming and bathing', 'Swimming and bathing', 'class', 'U044', True),
('LE04A -A', 'Swimming baths', 'Swimming baths', 'class', 'U044', True),
('LE03G', 'Target shooting places', 'Target shooting places', 'class', 'U044', True),
('LE03B -G', 'Ten pin bowling alley', 'Ten pin bowling alley', 'class', 'U044', True),
('LE03B -F', 'Tennis court', 'Tennis court', 'class', 'U044', True),
('LE04C', 'Water recreation places', 'Water recreation places', 'class', 'U044', True),
('LE04B -F', 'Water skiing place', 'Water skiing place', 'class', 'U044', False),
('LE04', 'Water sport places', 'Water sport places', 'class', 'U044', False),
('LE04B', 'Watercraft places', 'Watercraft places', 'class', 'U044', True),
('LE05A -A', 'Camping site', 'Camping site', 'class', 'U045', False),
('LE05A -B', 'Holiday camp site', 'Holiday camp site', 'class', 'U045', False),
('LE05A', 'Holiday camps', 'Holiday camps', 'class', 'U045', True),
('LE05A -C', 'Holiday caravan site', 'Holiday caravan site', 'class', 'U045', False),
('LE05A -D', 'Youth hostel', 'Youth hostel', 'class', 'U045', True),
('AG06B -A', 'Allotment gardens', 'Allotment gardens', 'class', 'U046', False),
('TR02C', 'Storage places for vehicles', 'Storage places for vehicles', 'class', 'U051', True),
('TR', 'Transport tracks and places', 'Transport tracks and places', 'class', 'U051', True),
('TR01E -A', 'Access road', 'Access road', 'class', 'U051', False),
('TR01E -B', 'All purpose road', 'All purpose road', 'class', 'U051', False),
('TR01F -A', 'Branch line', 'Branch line', 'class', 'U051', False),
('TR01C-A', 'Bridleway', 'Bridleway', 'class', 'U051', False),
('TR01D-A', 'Bus only way', 'Bus only way', 'class', 'U051', False),
('TR01D-B', 'Bus way', 'Bus way', 'class', 'U051', False),
('TR01B -A', 'Cycle track', 'Cycle track', 'class', 'U051', False),
('TR01C-B', 'Drovers way', 'Drovers way', 'class', 'U051', False),
('TR01A -A', 'Footpath', 'Footpath', 'class', 'U051', False),
('TR01', 'Land transport tracks', 'Land transport tracks', 'class', 'U051', False),
('TR01F -B', 'Light railway', 'Light railway', 'class', 'U051', False),
('TR01E -C', 'Local distributor road', 'Local distributor road', 'class', 'U051', False),
('TR01F -C', 'Main line', 'Main line', 'class', 'U051', False),
('TR01F -D', 'Mineral line', 'Mineral line', 'class', 'U051', False),
('TR01E -E', 'Motor vehicle practice circuit', 'Motor vehicle practice circuit', 'class', 'U051', False),
('TR01E -D', 'Motor vehicle testing circuit', 'Motor vehicle testing circuit', 'class', 'U051', False),
('TR01E -F', 'Motorway special road', 'Motorway special road', 'class', 'U051', False),
('TR01C-C', 'Pony trekking route', 'Pony trekking route', 'class', 'U051', False),
('TR01A -B', 'Precinct', 'Precinct', 'class', 'U051', False),
('TR01E -G', 'Primary distributor road', 'Primary distributor road', 'class', 'U051', False),
('TR01E -H', 'Processional route road', 'Processional route road', 'class', 'U051', False),
('TR01A -C', 'Processional route walking or marching', 'Processional route walking or marching', 'class', 'U051', False),
('TR01F', 'Railways', 'Railways', 'class', 'U051', False),
('TR01C-D', 'Ride', 'Ride', 'class', 'U051', False),
('TR01E', 'Roads', 'Roads', 'class', 'U051', False),
('TR01E -I', 'Secondary distributor road', 'Secondary distributor road', 'class', 'U051', False),
('TR01F -E', 'Tramway', 'Tramway', 'class', 'U051', False),
('TR01F -F', 'Underground line', 'Underground line', 'class', 'U051', False),
('TR01A -D', 'Walkway', 'Walkway', 'class', 'U051', False),
('TR02A -A', 'Aerial ropeway passenger terminal', 'Aerial ropeway passenger terminal', 'class', 'U051', True),
('TR02A -B', 'Air passenger terminal', 'Air passenger terminal', 'class', 'U051', True),
('TR02A -C', 'Airport', 'Airport', 'class', 'U051', True),
('TR02A -D', 'Bus station', 'Bus station', 'class', 'U051', True),
('TR02A -E', 'Bus stop', 'Bus stop', 'class', 'U051', True),
('TR02A -F', 'Car park', 'Car park', 'class', 'U051', True),
('TR02A -G', 'Coach station', 'Coach station', 'class', 'U051', True),
('TR02', 'Land transport places', 'Land transport places', 'class', 'U051', True),
('TR02A -H', 'Railway station', 'Railway station', 'class', 'U051', True),
('TR02A -I', 'Ship passenger terminal', 'Ship passenger terminal', 'class', 'U051', True),
('TR02A', 'Terminals and interchanges for people', 'Terminals and interchanges for people', 'class', 'U051', True),
('TR02C-C', 'Car storage place', 'Car storage place', 'class', 'U053', True),
('TR02C-A', 'Aircraft hangar', 'Aircraft hangar', 'class', 'U051', True),
('TR02C-B', 'Bus depot', 'Bus depot', 'class', 'U051', True),
('TR02C-D', 'Coach depot', 'Coach depot', 'class', 'U051', True),
('TR02C-E', 'Long stay lorry park', 'Long stay lorry park', 'class', 'U051', True),
('TR02C-F', 'Railway sidings', 'Railway sidings', 'class', 'U051', False),
('TR05A -A', 'Aerial ropeway', 'Aerial ropeway', 'class', 'U055', False),
('TR02B -A', 'Air freight terminal', 'Air freight terminal', 'class', 'U055', True),
('TR02B -B', 'Container depot', 'Container depot', 'class', 'U055', True),
('TR05A -B', 'Conveyor', 'Conveyor', 'class', 'U055', False),
('TR06A -A', 'Customs depot', 'Customs depot', 'class', 'U055', True),
('TR02B -C', 'Docks', 'Docks', 'class', 'U055', True),
('TR06', 'Goods handling places', 'Goods handling places', 'class', 'U055', True),
('TR05A -C', 'Lift', 'Lift', 'class', 'U055', True),
('TR02B -D', 'Lorry transhipment park', 'Lorry transhipment park', 'class', 'U055', False),
('TR05A', 'Mechanical handling places', 'Mechanical handling places', 'class', 'U055', True),
('TR02B -E', 'Railway goods siding', 'Railway goods siding', 'class', 'U055', False),
('TR02B -F', 'Railway goods yard', 'Railway goods yard', 'class', 'U055', False),
('TR02B -G', 'Railway sorting depot', 'Railway sorting depot', 'class', 'U055', True),
('TR02B', 'Terminals and interchanges for goods', 'Terminals and interchanges for goods', 'class', 'U055', True),
('TR04A -A', 'Anchorage', 'Anchorage', 'class', 'U056', False),
('TR04A -B', 'Boatyard', 'Boatyard', 'class', 'U056', False),
('TR03A -A', 'Canal', 'Canal', 'class', 'U056', False),
('TR04A -C', 'Marina', 'Marina', 'class', 'U056', False),
('TR04A -D', 'Mooring', 'Mooring', 'class', 'U056', False),
('TR03A -B', 'River', 'River', 'class', 'U056', False),
('TR04A', 'Storage places for water craft', 'Storage places for water craft', 'class', 'U056', True),
('TR03A', 'Water tracks', 'Water tracks', 'class', 'U056', False),
('TR04', 'Water transport places', 'Water transport places', 'class', 'U056', False),
('TR03', 'Water transport tracks', 'Water transport tracks', 'class', 'U056', False),
('UT', 'Utility services', 'Utility services', 'class', '#N/A', False),
('UT06A', 'District heating places', 'District heating places', 'class', 'U061', True),
('UT06A -A', 'District heating plant', 'District heating plant', 'class', 'U061', True),
('UT02B -A', 'Electricity cableway', 'Electricity cableway', 'class', 'U061', True),
('UT02B', 'Electricity distribution places', 'Electricity distribution places', 'class', 'U061', True),
('UT02A', 'Electricity production places', 'Electricity production places', 'class', 'U061', True),
('UT02', 'Electricity supply places', 'Electricity supply places', 'class', 'U061', True),
('UT02B -B', 'Electricity transformer station', 'Electricity transformer station', 'class', 'U061', True),
('UT01B', 'Gas distribution places', 'Gas distribution places', 'class', 'U061', True),
('UT01A -A', 'Gas holder', 'Gas holder', 'class', 'U061', True),
('UT01B -A', 'Gas pressure control station', 'Gas pressure control station', 'class', 'U061', True),
('UT01A', 'Gas production and storage places', 'Gas production and storage places', 'class', 'U061', True),
('UT01', 'Gas supply places', 'Gas supply places', 'class', 'U061', True),
('UT01A -B', 'Gas works', 'Gas works', 'class', 'U061', True),
('UT02A -A', 'Hydro electricity generating station', 'Hydro electricity generating station', 'class', 'U061', True),
('TR05B -A', 'Oil pumping station', 'Oil pumping station', 'class', 'U061', True),
('TR05B -B', 'Pipeline', 'Pipeline', 'class', 'U061', False),
('UT02A -B', 'Thermal electricity generating station', 'Thermal electricity generating station', 'class', 'U061', True),
('UT04A -A', 'Main drain', 'Main drain', 'class', 'U062', False),
('UT03A -A', 'Reservoir', 'Reservoir', 'class', 'U062', False),
('UT04', 'Sewage disposal places', 'Sewage disposal places', 'class', 'U062', True),
('UT04A', 'Sewage draining places', 'Sewage draining places', 'class', 'U062', True),
('UT04B -A', 'Sewage farm', 'Sewage farm', 'class', 'U062', True),
('UT04A -B', 'Sewage pumping station', 'Sewage pumping station', 'class', 'U062', True),
('UT04B', 'Sewage treatment places', 'Sewage treatment places', 'class', 'U062', True),
('UT04B -B', 'Sewage treatment works', 'Sewage treatment works', 'class', 'U062', True),
('UT03B', 'Water distribution places', 'Water distribution places', 'class', 'U062', True),
('UT03C', 'Water extraction places', 'Water extraction places', 'class', 'U062', True),
('UT03C-B', 'Water intake from rivers or streams', 'Water intake from rivers or streams', 'class', 'U062', True),
('UT03C-A', 'Water intake from springs', 'Water intake from springs', 'class', 'U062', True),
('UT03C-C', 'Water intake from underground sources', 'Water intake from underground sources', 'class', 'U062', True),
('UT03B -B', 'Water pipeline', 'Water pipeline', 'class', 'U062', True),
('UT03B -A', 'Water pumping station', 'Water pumping station', 'class', 'U062', True),
('UT03A', 'Water storage and treatment places', 'Water storage and treatment places', 'class', 'U062', True),
('UT03', 'Water supply places', 'Water supply places', 'class', 'U062', True),
('UT03A -B', 'Water tower', 'Water tower', 'class', 'U062', True),
('UT03A -C', 'Water treatment works', 'Water treatment works', 'class', 'U062', True),
('UT05A', 'Refuse disposal places', 'Refuse disposal places', 'class', 'U063', False),
('UT05', 'Refuse disposal places', 'Refuse disposal places', 'class', 'U063', False),
('UT05A -A', 'Refuse disposal plant', 'Refuse disposal plant', 'class', 'U063', False),
('UT05A -B', 'Refuse tip', 'Refuse tip', 'class', 'U063', False),
('UT07B -A', 'Cemetery', 'Cemetery', 'class', 'U064', False),
('UT07A -A', 'Chapel of rest', 'Chapel of rest', 'class', 'U064', True),
('UT07B -B', 'Crematorium', 'Crematorium', 'class', 'U064', True),
('UT07B', 'Dead bodies disposal places', 'Dead bodies disposal places', 'class', 'U064', True),
('UT07A', 'Dead bodies storage places', 'Dead bodies storage places', 'class', 'U064', True),
('UT07A -B', 'Mortuary', 'Mortuary', 'class', 'U064', True),
('UT08F', 'Direction finding places', 'Direction finding places', 'class', 'U065', True),
('UT08F -B', 'Direction finding transmitter', 'Direction finding transmitter', 'class', 'U065', True),
('UT08F -A', 'Navigational light beacon', 'Navigational light beacon', 'class', 'U065', False),
('UT08A', 'Postal service places', 'Postal service places', 'class', 'U065', True),
('UT08', 'Postal service, signalling and telecommunications places', 'Postal service, signalling and telecommunications places', 'class', 'U065', True),
('UT08A -A', 'Postal sorting depot', 'Postal sorting depot', 'class', 'U065', True),
('UT08C-A', 'Radar beacon', 'Radar beacon', 'class', 'U065', False),
('UT08C', 'Radar places', 'Radar places', 'class', 'U065', True),
('UT08C-B', 'Radar station', 'Radar station', 'class', 'U065', True),
('UT08D-B', 'Radio and television mast', 'Radio and television mast', 'class', 'U065', False),
('UT08D-A', 'Radio station', 'Radio station', 'class', 'U065', True),
('UT08E -A', 'Satellite communication station', 'Satellite communication station', 'class', 'U065', True),
('UT08F -C', 'Signalling station', 'Signalling station', 'class', 'U065', True),
('UT08B -A', 'Telephone cableway', 'Telephone cableway', 'class', 'U065', False),
('UT08B -B', 'Telephone exchange', 'Telephone exchange', 'class', 'U065', True),
('UT08B -C', 'Telephone kiosk', 'Telephone kiosk', 'class', 'U065', True),
('UT08D', 'Television and radio broadcasting places', 'Television and radio broadcasting places', 'class', 'U065', True),
('UT08D-C', 'Television station', 'Television station', 'class', 'U065', True),
('RS', 'Residences', 'Residences', 'class', '#N/A', False),
('RS02A -A', 'Building converted to more than one dwelling', 'Building converted to more than one dwelling', 'class', 'U071', True),
('RS02A -B', 'Bungalow', 'Bungalow', 'class', 'U071', True),
('RS02A -C', 'Detached house', 'Detached house', 'class', 'U071', True),
('RS02A', 'Dwellings', 'Dwellings', 'class', 'U071', True),
('RS02A -D', 'Maisonette', 'Maisonette', 'class', 'U071', True),
('RS01C-A', 'Movable dwelling site', 'Movable dwelling site', 'class', 'U071', False),
('RS02A -E', 'Non residential plus single dwelling', 'Non residential plus single dwelling', 'class', 'U071', True),
('RS02A -F', 'Purpose built block of flats', 'Purpose built block of flats', 'class', 'U071', True),
('RS01C-B', 'Residential caravan site', 'Residential caravan site', 'class', 'U071', False),
('RS02', 'Self contained residences', 'Self contained residences', 'class', 'U071', True),
('RS02A -G', 'Semi detached house', 'Semi detached house', 'class', 'U071', True),
('RS02A -H', 'Terraced house', 'Terraced house', 'class', 'U071', True),
('RS01A -A', 'Boarding house', 'Boarding house', 'class', 'U072', True),
('RS01', 'Group residences', 'Group residences', 'class', 'U072', True),
('RS01A -B', 'Hotel', 'Hotel', 'class', 'U072', True),
('RS01A -C', 'Residential club', 'Residential club', 'class', 'U072', True),
('RS01A -D', 'Rooming house', 'Rooming house', 'class', 'U072', True),
('RS01B -A', 'Barracks', 'Barracks', 'class', 'U073', True),
('CM04A -A', 'Children's home', 'Children's home', 'class', 'U073', True),
('RS01B', 'Communal homes', 'Communal homes', 'class', 'U073', True),
('CM04A -B', 'Handicapped and disabled people's home', 'Handicapped and disabled people's home', 'class', 'U073', True),
('CM04', 'Non medical care places', 'Non medical care places', 'class', 'U073', True),
('CM04A', 'Non medical homes', 'Non medical homes', 'class', 'U073', True),
('CM04A -C', 'Old people's home', 'Old people's home', 'class', 'U073', True),
('RS01B -B', 'Residential retreat', 'Residential retreat', 'class', 'U073', True),
('RS01B -C', 'School boarding house', 'School boarding house', 'class', 'U073', True),
('RS01B -D', 'Staff hostel', 'Staff hostel', 'class', 'U073', True),
('CM', 'Community and health services', 'Community and health services', 'class', '#N/A', False),
('CM01B -A', 'Ambulance station', 'Ambulance station', 'class', 'U081', True),
('CM01A -A', 'Ante natal and post natal clinic', 'Ante natal and post natal clinic', 'class', 'U081', True),
('CM01C-A', 'Artificial limb and appliance hospital', 'Artificial limb and appliance hospital', 'class', 'U081', True),
('CM01B', 'Auxiliary service centres medical', 'Auxiliary service centres medical', 'class', 'U081', True),
('CM01B -B', 'Blood transfusion centre', 'Blood transfusion centre', 'class', 'U081', True),
('CM01D-A', 'Convalescent home', 'Convalescent home', 'class', 'U081', True),
('CM04B -A', 'Counselling agency', 'Counselling agency', 'class', 'U081', True),
('CM04B', 'Counselling places', 'Counselling places', 'class', 'U081', True),
('CM01C-B', 'Dental hospital', 'Dental hospital', 'class', 'U081', True),
('CM01A -B', 'Dentist's surgery and consulting room', 'Dentist's surgery and consulting room', 'class', 'U081', True),
('CM01A -C', 'Dispensary', 'Dispensary', 'class', 'U081', True),
('CM01A -D', 'Doctor's surgery and consulting room', 'Doctor's surgery and consulting room', 'class', 'U081', True),
('CM01C-C', 'Ear, nose and throat hospital', 'Ear, nose and throat hospital', 'class', 'U081', True),
('CM01C-D', 'Eye hospital', 'Eye hospital', 'class', 'U081', True),
('CM01A -E', 'Eye clinic and optician's surgery and consulting room', 'Eye clinic and optician's surgery and consulting room', 'class', 'U081', True),
('CM01B -C', 'Family planning clinic', 'Family planning clinic', 'class', 'U081', True),
('CM01A -F', 'Foot clinic and chiropodist's surgery and consulting room', 'Foot clinic and chiropodist's surgery and consulting room', 'class', 'U081', True),
('CM01B -D', 'Forensic medicine centre', 'Forensic medicine centre', 'class', 'U081', True),
('CM01C-E', 'General hospital', 'General hospital', 'class', 'U081', True),
('CM01C-F', 'Geriatric hospital', 'Geriatric hospital', 'class', 'U081', True),
('CM01', 'Health care places', 'Health care places', 'class', 'U081', True),
('CM01A -G', 'Health centre', 'Health centre', 'class', 'U081', True),
('CM01A -H', 'Hearing aid centre', 'Hearing aid centre', 'class', 'U081', True),
('CM01C', 'Hospitals', 'Hospitals', 'class', 'U081', True),
('CM01C-G', 'Isolation hospital', 'Isolation hospital', 'class', 'U081', True),
('CM01C-H', 'Maternity hospital', 'Maternity hospital', 'class', 'U081', True),
('CM01B', 'Medical auxiliary service centres', 'Medical auxiliary service centres', 'class', 'U081', True),
('CM01A', 'Medical diagnosis and treatment centres', 'Medical diagnosis and treatment centres', 'class', 'U081', True),
('CM02A', 'Medical research establishments', 'Medical research establishments', 'class', 'U081', True),
('CM02A -A', 'Medical research laboratory', 'Medical research laboratory', 'class', 'U081', True),
('CM01C-I', 'Mental hospital', 'Mental hospital', 'class', 'U081', True),
('CM01A -I', 'Mental clinic', 'Mental clinic', 'class', 'U081', True),
('CM01A -J', 'Nervous disorders clinic', 'Nervous disorders clinic', 'class', 'U081', True),
('CM01A -K', 'Occupational therapy and physiotherapy clinic', 'Occupational therapy and physiotherapy clinic', 'class', 'U081', True),
('CM01C-J', 'Orthopaedic hosdpital', 'Orthopaedic hosdpital', 'class', 'U081', True),
('CM01A -L', 'Orthopaedic and rheumatic clinic', 'Orthopaedic and rheumatic clinic', 'class', 'U081', True),
('CM01B -E', 'Radiography centre', 'Radiography centre', 'class', 'U081', True),
('CM01A -M', 'Surgeon's surgery and consulting room', 'Surgeon's surgery and consulting room', 'class', 'U081', True),
('CM07A', 'Places of worship', 'Places of worship', 'class', 'U082', True),
('ED01F -A', 'Adult education centre', 'Adult education centre', 'class', 'U083', True),
('ED02A -A', 'Archaeological site', 'Archaeological site', 'class', 'U083', False),
('ED01F -B', 'College of further education', 'College of further education', 'class', 'U083', True),
('ED01F -C', 'College of technology', 'College of technology', 'class', 'U083', True),
('ED01A -A', 'Day nursery school', 'Day nursery school', 'class', 'U083', True),
('ED01', 'Education places', 'Education places', 'class', 'U083', True),
('ED01B -A', 'Infant school', 'Infant school', 'class', 'U083', True),
('ED01B -B', 'Junior school', 'Junior school', 'class', 'U083', True),
('ED01C-A', 'Middle school', 'Middle school', 'class', 'U083', True),
('ED02B -A', 'Nature reserve', 'Nature reserve', 'class', 'U083', False),
('ED02B', 'Nature reserves and sanctuaries', 'Nature reserves and sanctuaries', 'class', 'U083', False),
('ED01A -B', 'Nursery school', 'Nursery school', 'class', 'U083', True),
('ED02A -B', 'Observatory', 'Observatory', 'class', 'U083', True),
('ED01F -D', 'Polytechnic', 'Polytechnic', 'class', 'U083', True),
('ED01A', 'Pre primary schools', 'Pre primary schools', 'class', 'U083', True),
('ED01B', 'Primary schools', 'Primary schools', 'class', 'U083', True),
('ED02A', 'Research establishments', 'Research establishments', 'class', 'U083', True),
('ED02', 'Research places', 'Research places', 'class', 'U083', True),
('ED01D-A', 'Secondary school', 'Secondary school', 'class', 'U083', True),
('ED01D', 'Secondary schools', 'Secondary schools', 'class', 'U083', True),
('ED02B -B', 'Site of special scientific interest', 'Site of special scientific interest', 'class', 'U083', False),
('ED01D-B', 'Sixth form college', 'Sixth form college', 'class', 'U083', True),
('ED01E -A', 'Special school', 'Special school', 'class', 'U083', True),
('ED01F', 'Specialised, higher and further education centres', 'Specialised, higher and further education centres', 'class', 'U083', True),
('ED01F -E', 'Teacher training college', 'Teacher training college', 'class', 'U083', True),
('ED01F -F', 'Technical college', 'Technical college', 'class', 'U083', True),
('ED01F -G', 'University teaching establishment', 'University teaching establishment', 'class', 'U083', True),
('CM06A -A', 'Advertising hoarding', 'Advertising hoarding', 'class', 'U084', False),
('CM06A', 'Advertising places', 'Advertising places', 'class', 'U084', False),
('CM05A -A', 'Approved school', 'Approved school', 'class', 'U084', True),
('CM08A -A', 'Arbitration court', 'Arbitration court', 'class', 'U084', True),
('CM05A -B', 'Borstal institution', 'Borstal institution', 'class', 'U084', True),
('CM06B -A', 'Church hall', 'Church hall', 'class', 'U084', True),
('CM05B -A', 'Civil Defence centre', 'Civil Defence centre', 'class', 'U084', True),
('CM06B -B', 'Club meeting place', 'Club meeting place', 'class', 'U084', True),
('CM05B -B', 'Coastguard station', 'Coastguard station', 'class', 'U084', True),
('CM06', 'Communication places', 'Communication places', 'class', 'U084', True),
('CM06B -C', 'Community centre', 'Community centre', 'class', 'U084', True),
('CM05', 'Community protection services', 'Community protection services', 'class', 'U084', True),
('CM08A', 'Courts', 'Courts', 'class', 'U084', True),
('CM05A', 'Detention places', 'Detention places', 'class', 'U084', True),
('CM05B -C', 'Fire station', 'Fire station', 'class', 'U084', True),
('CM08', 'Justice administration places', 'Justice administration places', 'class', 'U084', True),
('CM08A -B', 'Law court', 'Law court', 'class', 'U084', True),
('CM05B -E', 'Life boat station', 'Life boat station', 'class', 'U084', True),
('CM07A -A', 'Place of worship', 'Place of worship', 'class', 'U084', True),
('CM05B -D', 'Police station', 'Police station', 'class', 'U084', True),
('CM05A -C', 'Prison', 'Prison', 'class', 'U084', True),
('CM05A -D', 'Prison rehabilitation centre', 'Prison rehabilitation centre', 'class', 'U084', True),
('CM05B', 'Protection places', 'Protection places', 'class', 'U084', True),
('CM03A -A', 'Public bath', 'Public bath', 'class', 'U084', True),
('CM03A -B', 'Public convenience', 'Public convenience', 'class', 'U084', True),
('CM05A -E', 'Remand centre', 'Remand centre', 'class', 'U084', True),
('CM05A -F', 'Remand classifying centre', 'Remand classifying centre', 'class', 'U084', True),
('CM05A -G', 'Remand home', 'Remand home', 'class', 'U084', True),
('CM03', 'Sanitation places', 'Sanitation places', 'class', 'U084', True),
('CM03A', 'Sanitation places', 'Sanitation places', 'class', 'U084', True),
('CM06B', 'Social meeting places', 'Social meeting places', 'class', 'U084', True),
('CM08A -C', 'Tribunal place', 'Tribunal place', 'class', 'U084', True),
('RT03', 'Catering service places', 'Catering service places', 'class', 'U093', True),
('RT01', 'Retail distribution places', 'Retail distribution places', 'class', 'U091', True),
('RT', 'Retail distribution and servicing places', 'Retail distribution and servicing places', 'class', 'U091', True),
('RT01A -A', 'Baker’s shop', 'Baker’s shop', 'class', 'U091', True),
('RT01B -A', 'Beauty salon', 'Beauty salon', 'class', 'U091', True),
('RT02B -A', 'Boot and shoe repair establishment', 'Boot and shoe repair establishment', 'class', 'U091', True),
('RT01A -B', 'Butcher's shop', 'Butcher's shop', 'class', 'U091', True),
('RT01D-A', 'Caravan sales place', 'Caravan sales place', 'class', 'U091', True),
('RT01F -A', 'Cash and carry store', 'Cash and carry store', 'class', 'U091', True),
('RT01A -C', 'Cats meat shop', 'Cats meat shop', 'class', 'U091', True),
('RT01B -C', 'Clothing and footwear shop', 'Clothing and footwear shop', 'class', 'U091', True),
('RT01B -B', 'Confectionery, tobacco and newspaper shop', 'Confectionery, tobacco and newspaper shop', 'class', 'U091', True),
('RT01A -D', 'Dairy shop', 'Dairy shop', 'class', 'U091', True),
('RT01F -B', 'Department store', 'Department store', 'class', 'U091', True),
('RT02B -B', 'Dry cleaning and clothing repair establishment', 'Dry cleaning and clothing repair establishment', 'class', 'U091', True),
('RT01B -D', 'Duplicating and copying centre', 'Duplicating and copying centre', 'class', 'U091', True),
('RT01C-A', 'Electricity showroom', 'Electricity showroom', 'class', 'U091', True),
('RT01A -E', 'Fish shop', 'Fish shop', 'class', 'U091', True),
('RT01A', 'Food and drink shops', 'Food and drink shops', 'class', 'U091', True),
('RT01A -F', 'Fried fish shop', 'Fried fish shop', 'class', 'U091', True),
('RT01A -G', 'Frozen food shop', 'Frozen food shop', 'class', 'U091', True),
('RT01C-B', 'Gas showroom', 'Gas showroom', 'class', 'U091', True),
('RT01B -E', 'General stores', 'General stores', 'class', 'U091', True),
('RT01A -H', 'Green grocer's shop', 'Green grocer's shop', 'class', 'U091', True),
('RT01A -I', 'Grocery and provision', 'Grocery and provision', 'class', 'U091', True),
('RT01B -F', 'Hairdresser's shop', 'Hairdresser's shop', 'class', 'U091', True),
('RT01A -J', 'Hot food shop', 'Hot food shop', 'class', 'U091', True),
('RT01C-C', 'Household goods shop', 'Household goods shop', 'class', 'U091', True),
('RT01C', 'Household goods shops and showrooms', 'Household goods shops and showrooms', 'class', 'U091', True),
('RT01F', 'Hybrid shops and stores', 'Hybrid shops and stores', 'class', 'U091', True),
('RT01F -C', 'Hypermarket', 'Hypermarket', 'class', 'U091', True),
('RT02B -C', 'Launderette', 'Launderette', 'class', 'U091', True),
('RT02B -D', 'Laundry cleaning only', 'Laundry cleaning only', 'class', 'U091', True),
('RT01B -G', 'Laundry, cleaning and repairing shop receiving', 'Laundry, cleaning and repairing shop receiving', 'class', 'U091', True),
('RT02', 'Maintenance and repair places', 'Maintenance and repair places', 'class', 'U091', True),
('RT01D-C', 'Motor vehicle dealer display area', 'Motor vehicle dealer display area', 'class', 'U091', True),
('RT01D', 'Motor vehicle goods shops and filling stations', 'Motor vehicle goods shops and filling stations', 'class', 'U091', True),
('RT02A', 'Motor vehicle maintenance and repair places', 'Motor vehicle maintenance and repair places', 'class', 'U091', True),
('RT02A -A', 'Motor vehicle repair garage', 'Motor vehicle repair garage', 'class', 'U091', True),
('RT01D-D', 'Motor vehicle sales', 'Motor vehicle sales', 'class', 'U091', True),
('RT01D-B', 'Motor vehicle spare parts and accessories', 'Motor vehicle spare parts and accessories', 'class', 'U091', True),
('RT02A -B', 'Motor vehicle testing station', 'Motor vehicle testing station', 'class', 'U091', True),
('RT01A -K', 'Off licence', 'Off licence', 'class', 'U091', True),
('RT02B', 'Personal and household goods repair and cleaning places', 'Personal and household goods repair and cleaning places', 'class', 'U091', True),
('RT01B -H', 'Pet animal and bird shop', 'Pet animal and bird shop', 'class', 'U091', True),
('RT01D-E', 'Petrol and oil filling station', 'Petrol and oil filling station', 'class', 'U091', True),
('RT01B -I', 'Photographic service shop', 'Photographic service shop', 'class', 'U091', True),
('RT01B -J', 'Post office', 'Post office', 'class', 'U091', True),
('RT01E -A', 'Retail market place', 'Retail market place', 'class', 'U091', True),
('RT01F -D', 'Supermarket', 'Supermarket', 'class', 'U091', True),
('RT01B -K', 'Ticket agency', 'Ticket agency', 'class', 'U091', True),
('RT01B -L', 'Travel agency', 'Travel agency', 'class', 'U091', True),
('RT01A -L', 'Tripe shop', 'Tripe shop', 'class', 'U091', True),
('RT01D-F', 'Tyre retailing and fitting place', 'Tyre retailing and fitting place', 'class', 'U091', True),
('RT01B -M', 'Undertaker', 'Undertaker', 'class', 'U091', True),
('OF02A -A', 'Bank', 'Bank', 'class', 'U092', True),
('LE01C-B', 'Betting office', 'Betting office', 'class', 'U092', True),
('OF02A -B', 'Building society office', 'Building society office', 'class', 'U092', True),
('OF02A', 'Financial service offices', 'Financial service offices', 'class', 'U092', True),
('OF02A -C', 'Insurance office', 'Insurance office', 'class', 'U092', True),
('RT03B', 'Catering places', 'Catering places', 'class', 'U093', True),
('RT03B -A', 'Restaurant', 'Restaurant', 'class', 'U093', True),
('RT03A -A', 'Public house', 'Public house', 'class', 'U094', True);

